class Status:
    PENDING={
        "code":1,
        "value":"pending"
    }
    APPROVED={
        "code":2,
        "value":"approved"
    }
    FAILURE={
        "code":3,
        "value":"failure"
    }
    SUCCESS={
        "code":4,
        "value":"success"
    }
    REJECTED={
        "code":5,
        "value":"rejected"
    }
    CANCELLED={
        "code":6,
        "value":"cancelled"
    }

class Role:
    ADMIN={
        "code":1,
        "value":"admin"
    }
    STUDENT={
        "code":2,
        "value":"user"
    }
    SUPER_ADMIN={
        "code":3,
        "value":"super_admin"
    }
    TEACHER={
        "code":4,
        "value":"teacher"
    }

class ApprovalType:
    REGISTRATION={
        "code":1,
        "value":"registration"
    }
    COURSE={
        "code":2,
        "value":"course"
    }
    BLOCK={
        "code":3,
        "value":"block"
    }
    UNBLOCK={
        "code":4,
        "value":"unblock"
    }
    DELETE={
        "code":5,
        "value":"delete"
    }
    UPDATE={
        "code":6,
        "value":"update"
    }
    ADD={
        "code":7,
        "value":"add"
    }